apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - networkpolicy.yaml
patches:
  - path: statefulset-patch.yaml
  - path: service-patch.yaml
  - path: pdb-patch.yaml
  - path: delete-resources.yaml
