apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - minio.yaml
  - minio-init.yaml
  - statefulset.yaml
  - goauthy-pdb.yaml
  - networkpolicy.yaml
