apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goauthy
resources:
  - ../k8s
configMapGenerator:
  - name: geoblock-country-db
    files:
      - country.mmdb=testdata/country.mmdb
    options:
      disableNameSuffixHash: true
patches:
  - path: statefulset-patch.yaml
