const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync(__dirname + '/catalog.js', 'utf8');
const elements = new Map(), calls = [], app = {innerHTML: ''};
const document = {getElementById(id) { if (!elements.has(id)) elements.set(id, {innerHTML: '', value: '', checked: false, textContent: '', className: '', disabled: false}); return elements.get(id); }};
const ctx = {document, console, confirm: () => true, encodeURIComponent, root: app,
  location: {href: ''},
  esc: v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),
  split: v => v.split(',').map(x => x.trim()).filter(Boolean), shell: (_, __, body) => { app.innerHTML = body; for (const id of ['catalog-status', 'catalog-list', 'catalog-form', 'catalog-name', 'catalog-desc', 'catalog-default', 'catalog-type', 'catalog-editable', 'catalog-access', 'catalog-id', 'catalog-root', 'catalog-result', 'catalog-submit', 'catalog-cancel', 'catalog-delete']) document.getElementById(id).disabled = !!ctx.preDisabled?.has(id); document.getElementById('catalog-form').querySelectorAll = () => ['catalog-name', 'catalog-desc', 'catalog-default', 'catalog-type', 'catalog-editable', 'catalog-access', 'catalog-id', 'catalog-root', 'catalog-submit', 'catalog-delete'].map(document.getElementById); },
  api: async (url, opts = {}) => { calls.push({url, opts}); if (ctx.holdWrite && opts.method) return new Promise((resolve, reject) => { ctx.resolveWrite = resolve; ctx.rejectWrite = reject; }); if (ctx.failNext) { ctx.failNext = false; throw Error('backend unavailable'); } return opts.method ? {} : (url.includes('/attr') ? {values: [{name: 'staff', desc: '<x>', default_value: false, typ: 'email', user_editable: true}]} : [{scope: 'staff', attr_include_access: ['staff'], attr_include_id: []}]); }};
vm.runInNewContext(source, ctx);
(async () => {
  await ctx.catalog('attributes');
  assert.match(document.getElementById('catalog-list').innerHTML, /staff/);
  await ctx.catalog('attributes', 'staff');
  document.getElementById('catalog-desc').value = 'changed';
  document.getElementById('catalog-default').value = 'false';
  await document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  assert.equal(calls.filter(call => call.opts.method).at(-1).url, '/auth/v1/users/attr/staff');
  assert.equal(calls.filter(call => call.opts.method).at(-1).opts.method, 'PUT');
  assert.equal(JSON.parse(calls.filter(call => call.opts.method).at(-1).opts.body).default_value, false);
  assert.equal(ctx.location.href, '/auth/v1/admin/attributes');
  await ctx.catalog('attributes', 'staff');
  document.getElementById('catalog-default').value = '';
  await document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  assert.equal('default_value' in JSON.parse(calls.filter(call => call.opts.method).at(-1).opts.body), false);
  await ctx.catalog('attributes', 'new');
  assert.match(app.innerHTML, /Cancel/);
  document.getElementById('catalog-name').value = 'new-attr';
  document.getElementById('catalog-default').value = '{"enabled":true}';
  await document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  assert.equal(calls.filter(call => call.opts.method).at(-1).url, '/auth/v1/users/attr');
  assert.equal(calls.filter(call => call.opts.method).at(-1).opts.method, 'POST');
  assert.deepEqual(JSON.parse(calls.filter(call => call.opts.method).at(-1).opts.body).default_value, {enabled: true});
  await ctx.catalog('attributes', 'new');
  const writesBeforeInvalidJSON = calls.filter(call => call.opts.method).length;
  document.getElementById('catalog-default').value = '{invalid';
  await document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  assert.equal(calls.filter(call => call.opts.method).length, writesBeforeInvalidJSON);
  assert.equal(document.getElementById('catalog-result').textContent, 'Default value must be valid JSON.');
  assert.equal(document.getElementById('catalog-submit').disabled, false);
  await ctx.catalog('scopes', 'new');
  document.getElementById('catalog-name').value = 'new-scope';
  document.getElementById('catalog-access').value = 'staff';
  await document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  assert.equal(calls.filter(call => call.opts.method).at(-1).url, '/auth/v1/scopes');
  assert.equal(calls.filter(call => call.opts.method).at(-1).opts.method, 'POST');
  assert.deepEqual(JSON.parse(calls.filter(call => call.opts.method).at(-1).opts.body).attr_include_access, ['staff']);
  ctx.preDisabled = new Set(['catalog-name']);
  await ctx.catalog('scopes', 'new');
  ctx.preDisabled = null;
  document.getElementById('catalog-name').value = 'pending-scope';
  ctx.holdWrite = true;
  const pendingCalls = calls.filter(call => call.opts.method).length;
  const submit = document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  await Promise.resolve();
  assert.equal(document.getElementById('catalog-submit').disabled, true);
  let cancelPrevented = false;
  assert.equal(document.getElementById('catalog-cancel').disabled, false);
  document.getElementById('catalog-cancel').onclick({preventDefault() { cancelPrevented = true; }});
  assert.equal(cancelPrevented, true);
  await document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  assert.equal(calls.filter(call => call.opts.method).length, pendingCalls + 1);
  ctx.rejectWrite(Error('backend unavailable'));
  await submit;
  assert.equal(document.getElementById('catalog-submit').disabled, false);
  assert.equal(document.getElementById('catalog-name').disabled, true);
  cancelPrevented = false;
  document.getElementById('catalog-cancel').onclick({preventDefault() { cancelPrevented = true; }});
  assert.equal(cancelPrevented, false);
  ctx.holdWrite = false;
  await ctx.catalog('scopes', 'staff');
  ctx.holdWrite = true;
  const update = document.getElementById('catalog-form').onsubmit({preventDefault() {}});
  await Promise.resolve();
  const pendingUpdateCalls = calls.filter(call => call.opts.method).length;
  await document.getElementById('catalog-delete').onclick();
  assert.equal(calls.filter(call => call.opts.method).length, pendingUpdateCalls);
  ctx.rejectWrite(Error('backend unavailable'));
  await update;
  ctx.holdWrite = false;
  ctx.failNext = true;
  await ctx.catalog('attributes');
  assert.match(document.getElementById('catalog-list').innerHTML, /backend unavailable/);
  await ctx.catalog('scopes', 'staff');
  await document.getElementById('catalog-delete').onclick();
  assert.equal(calls.filter(call => call.opts.method).at(-1).url, '/auth/v1/scopes/staff');
  assert.equal(calls.filter(call => call.opts.method).at(-1).opts.method, 'DELETE');
  assert.equal(ctx.location.href, '/auth/v1/admin/scopes');
  console.log('catalog UI behavioral checks passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
