const clientWebScopes=['openid','email','profile','groups'],clientDeviceScopes=['goauthy.read','offline_access'];
const clientWebFlow='authorization_code',clientDeviceFlow='urn:ietf:params:oauth:grant-type:device_code',clientRefreshFlow='refresh_token',clientCredentialsFlow='client_credentials';
const clientFlows=[clientWebFlow,clientRefreshFlow,clientCredentialsFlow,clientDeviceFlow];
const clientValues=v=>String(v??'').split(/[\s,]+/).map(x=>x.trim()).filter(Boolean);
const clientRedirects=v=>String(v??'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const clientLines=v=>(v||[]).join('\n');
function clientChecks(id,values,labels){return labels.map(x=>`<label><input type="checkbox" id="${id}-${esc(x).replace(/[^A-Za-z0-9_-]/g,'-')}" data-${id}="${esc(x)}" ${values.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}
function clientForm(id,current={},editing=false){
  const c=current||{}, confidential=c.confidential!==false, flows=c.enabled_flows||[], scopes=c.scopes||[], defaults=c.default_scopes||[], audience=c.audience||[], forceMfa=c.force_mfa||false;
  shell(`${editing?'Edit':'New'} OAuth client`,editing?`Update ${esc(c.name||id)} without changing its ID.`:'Register a managed OAuth client.',`<div class="panel"><form id="client-form">
    <label for="client-id">Client ID<input id="client-id" required pattern="[A-Za-z0-9._-]{2,256}" value="${esc(id||'')}" ${editing?'readonly':''}></label>
    <label for="client-name">Name<input id="client-name" value="${esc(c.name||'')}"></label>
    <fieldset><legend>Client type</legend><div class="checks"><label><input id="client-confidential" type="checkbox" ${confidential?'checked':''}> Confidential (has a secret)</label></div><p class="hint">Public device-only clients do not use redirect URIs; public web clients do.</p></fieldset>
    <div class="toolbar"><strong>Preset</strong><span><button type="button" class="button secondary" id="client-web">Web</button> <button type="button" class="button secondary" id="client-device">Device</button></span></div>
    <label for="client-redirects">Redirect URIs <span class="hint">One per line</span><textarea id="client-redirects">${esc(clientLines(c.redirect_uris))}</textarea></label>
    <label for="client-audience">Resource audiences <span class="hint">One HTTPS resource per line</span><textarea id="client-audience">${esc(clientLines(audience))}</textarea></label>
    <label for="client-scopes">Allowed scopes <span class="hint">One per line</span><textarea id="client-scopes">${esc(clientLines(scopes))}</textarea></label>
    <label for="client-default-scopes">Default scopes <span class="hint">One per line</span><textarea id="client-default-scopes">${esc(clientLines(defaults))}</textarea></label>
    <fieldset><legend>Grant flows</legend><div class="checks" id="client-flows">${clientChecks('client-flow',flows,clientFlows)}</div></fieldset>
    <label class="checks"><span><input id="client-force-mfa" type="checkbox" ${forceMfa?'checked':''}> Force MFA</span></label>
    ${editing?`<label class="checks"><span><input id="client-enabled" type="checkbox" ${c.enabled?'checked':''}> Enabled</span></label>`:''}
    <div class="actions"><button id="client-save" type="submit">${editing?'Save changes':'Create client'}</button><a class="button secondary" href="/auth/v1/admin/clients">Cancel</a>${editing?'<button type="button" id="client-delete" class="button secondary">Delete</button>':''}<span id="client-result" role="status"></span></div>
    ${editing&&confidential?'<section><h2>Secret</h2><div id="client-secret" class="hint">Secret is only retrieved when requested.</div><div class="actions"><button type="button" id="client-secret-read" class="button secondary">Read secret</button><button type="button" id="client-secret-rotate" class="button secondary">Rotate secret</button><button type="button" id="client-secret-hide" class="button secondary">Hide</button></div></section>':''}
  </form></div>`);
  const by=id=>document.getElementById(id), result=by('client-result'); let pending=false,secret='';
  const busy=v=>document.querySelectorAll('#client-form button').forEach(x=>x.disabled=v);
  const setSecret=v=>{secret=v||'';const out=by('client-secret');if(out)out.textContent=secret||'Secret is hidden.'};
  const setPreset=device=>{by('client-confidential').checked=!device;by('client-redirects').value=device?'':by('client-redirects').value;by('client-scopes').value=(device?clientDeviceScopes:clientWebScopes.concat(['offline_access'])).join('\n');by('client-default-scopes').value=(device?clientDeviceScopes:['openid']).join('\n');document.querySelectorAll('[data-client-flow]').forEach(x=>x.checked=(device?[clientDeviceFlow,clientRefreshFlow]:[clientWebFlow,clientRefreshFlow]).includes(x.dataset.clientFlow));};
  by('client-web').onclick=()=>setPreset(false);by('client-device').onclick=()=>setPreset(true);
  if(editing&&confidential){by('client-secret-hide').onclick=()=>setSecret('');by('client-secret-read').onclick=async()=>{if(pending)return;setSecret('');pending=true;busy(true);try{const j=await api('/auth/v1/clients/'+encodeURIComponent(id)+'/secret',{method:'POST',body:''});setSecret(typeof j==='string'?j:j.secret)}catch(e){setSecret('');result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}};by('client-secret-rotate').onclick=async()=>{if(pending)return;setSecret('');pending=true;busy(true);try{const j=await api('/auth/v1/clients/'+encodeURIComponent(id)+'/secret',{method:'PUT',body:'',headers:{'If-Match':'"'+c.revision+'"'}});const etag=j._headers?.get?.('ETag')?.replaceAll('"',''),revision=Number(etag||j.revision||0);if(!revision)throw Error('Secret rotated, but the new revision was not returned; reload before making another change.');c.revision=revision;setSecret(typeof j==='string'?j:j.secret)}catch(e){setSecret('');result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}}}
  by('client-form').onsubmit=async e=>{e.preventDefault();if(pending)return;const confidential=by('client-confidential').checked,redirects=clientRedirects(by('client-redirects').value),audience=clientRedirects(by('client-audience').value),scopes=clientValues(by('client-scopes').value),defaults=clientValues(by('client-default-scopes').value),enabledFlows=[...document.querySelectorAll('[data-client-flow]:checked')].map(x=>x.dataset.clientFlow),forceMfa=by('client-force-mfa').checked;if(!enabledFlows.length){result.className='error';result.textContent='Select at least one grant flow.';return}if(!confidential&&enabledFlows.includes(clientCredentialsFlow)){result.className='error';result.textContent='Public clients cannot use client credentials.';return}if(enabledFlows.includes(clientWebFlow)&&!redirects.length){result.className='error';result.textContent='Authorization code clients need a redirect URI.';return}const body={name:by('client-name').value||null,confidential,redirect_uris:redirects,audience,scopes,default_scopes:defaults,enabled_flows:enabledFlows,force_mfa:forceMfa};if(editing){body.enabled=by('client-enabled').checked} else body.id=by('client-id').value;
  setSecret('');pending=true;busy(true);try{const out=await api('/auth/v1/clients'+(editing?'/'+encodeURIComponent(id):''),{method:editing?'PUT':'POST',body:JSON.stringify(body),headers:editing?{'If-Match':'"'+c.revision+'"'}:{}});result.className='success';result.textContent='Saved';if(!editing)location.href='/auth/v1/admin/clients/'+encodeURIComponent(body.id)+'/edit';else{const etag=out._headers?.get?.('ETag')?.replaceAll('"','');c.revision=Number(etag||out.revision||0)||c.revision;await clients(id,'edit')}}catch(err){setSecret('');result.className='error';result.textContent=String(err.message).startsWith('409')?'Conflict — reload to review the latest client; your form is preserved.':err.message}finally{pending=false;busy(false)}};
  if(editing)by('client-delete').onclick=async()=>{if(pending||!confirm('Delete client '+id+' permanently?'))return;setSecret('');pending=true;busy(true);try{await api('/auth/v1/clients/'+encodeURIComponent(id),{method:'DELETE',body:'',headers:{'If-Match':'"'+c.revision+'"'}});location.href='/auth/v1/admin/clients'}catch(e){result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}};
}
async function clients(id,mode){if(!id){shell('Clients','Manage OAuth clients registered for this service.','<div class="toolbar"><span id="client-status" class="hint">Loading…</span><a class="button" href="/auth/v1/admin/clients/new">New client</a></div><div id="client-list"></div>');try{const rows=await api('/auth/v1/clients');document.getElementById('client-status').textContent=rows.length+' clients';document.getElementById('client-list').innerHTML=rows.length?`<table><thead><tr><th>Name</th><th>Client ID</th><th>Type</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td><a href="/auth/v1/admin/clients/${encodeURIComponent(x.id)}/edit">${esc(x.name||x.id)}</a></td><td>${esc(x.id)}</td><td>${x.confidential?'Confidential':'Public'}</td><td>${x.enabled?'Enabled':'Disabled'}</td></tr>`).join('')}</tbody></table>`:'<p class="state">No managed clients yet.</p>'}catch(e){document.getElementById('client-list').innerHTML='<p class="error">'+esc(e.message)+'</p>'}return}if(mode==='new'){return clientForm('',{},false)}try{const c=await api('/auth/v1/clients/'+encodeURIComponent(id));return clientForm(id,c,true)}catch(e){shell('Client unavailable','',`<p class="error">${esc(e.message)}</p>`)} }
