const clientWebScopes=['openid','email','profile','groups'],clientDeviceScopes=['goauthy.read','offline_access'];
const clientWebFlow='authorization_code',clientDeviceFlow='urn:ietf:params:oauth:grant-type:device_code',clientRefreshFlow='refresh_token',clientCredentialsFlow='client_credentials';
const clientFlows=[clientWebFlow,clientRefreshFlow,clientCredentialsFlow,clientDeviceFlow];
const clientValues=v=>String(v??'').split(/[\s,]+/).map(x=>x.trim()).filter(Boolean);
const clientRedirects=v=>String(v??'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const clientLines=v=>(v||[]).join('\n');
function clientChecks(id,values,labels){return labels.map(x=>`<label><input type="checkbox" id="${id}-${esc(x).replace(/[^A-Za-z0-9_-]/g,'-')}" data-${id}="${esc(x)}" ${values.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}
function clientForm(id,current={},editing=false,t=(key,values={})=>String(key).replace(/\{(\w+)\}/g,(match,name)=>Object.hasOwn(values,name)?String(values[name]):match)){
  const h=(key,values)=>esc(t(key,values));
  const c=current||{}, confidential=c.confidential!==false, flows=c.enabled_flows||[], scopes=c.scopes||[], defaults=c.default_scopes||[], audience=c.audience||[], forceMfa=c.force_mfa||false;
  shell(t(editing?'Edit OAuth client':'New OAuth client'),editing?t('Update {name} without changing its ID.',{name:esc(c.name||id)}):t('Register a managed OAuth client.'),`${editing?`<p><a class="button secondary" href="/auth/v1/admin/clients/${encodeURIComponent(id)}/theme">${h('Login appearance')}</a></p>`:''}<div class="panel"><form id="client-form">
    <label for="client-id">${h('Client ID')}<input id="client-id" required pattern="[A-Za-z0-9._-]{2,256}" value="${esc(id||'')}" ${editing?'readonly':''}></label>
    <label for="client-name">${h('Name')}<input id="client-name" value="${esc(c.name||'')}"></label>
    <fieldset><legend>${h('Client type')}</legend><div class="checks"><label><input id="client-confidential" type="checkbox" ${confidential?'checked':''}> ${h('Confidential (has a secret)')}</label></div><p class="hint">${h('Public device-only clients do not use redirect URIs; public web clients do.')}</p></fieldset>
    <div class="toolbar"><strong>${h('Preset')}</strong><span><button type="button" class="button secondary" id="client-web">${h('Web')}</button> <button type="button" class="button secondary" id="client-device">${h('Device')}</button></span></div>
    <label for="client-redirects">${h('Redirect URIs')} <span class="hint">${h('One per line')}</span><textarea id="client-redirects">${esc(clientLines(c.redirect_uris))}</textarea></label>
    <label for="client-audience">${h('Resource audiences')} <span class="hint">${h('One HTTPS resource per line')}</span><textarea id="client-audience">${esc(clientLines(audience))}</textarea></label>
    <label for="client-scopes">${h('Allowed scopes')} <span class="hint">${h('One per line')}</span><textarea id="client-scopes">${esc(clientLines(scopes))}</textarea></label>
    <label for="client-default-scopes">${h('Default scopes')} <span class="hint">${h('One per line')}</span><textarea id="client-default-scopes">${esc(clientLines(defaults))}</textarea></label>
    <fieldset><legend>${h('Grant flows')}</legend><div class="checks" id="client-flows">${clientChecks('client-flow',flows,clientFlows)}</div></fieldset>
    <label class="checks"><span><input id="client-force-mfa" type="checkbox" ${forceMfa?'checked':''}> ${h('Force MFA')}</span></label>
    ${editing?`<label class="checks"><span><input id="client-enabled" type="checkbox" ${c.enabled?'checked':''}> ${h('Enabled')}</span></label>`:''}
    <div class="actions"><button id="client-save" type="submit">${h(editing?'Save changes':'Create client')}</button><a class="button secondary" href="/auth/v1/admin/clients">${h('Cancel')}</a>${editing?'<button type="button" id="client-delete" class="button secondary">'+h('Delete')+'</button>':''}<span id="client-result" role="status"></span></div>
    ${editing&&confidential?'<section><h2>'+h('Secret')+'</h2><div id="client-secret" class="hint">'+h('Secret is only retrieved when requested.')+'</div><div class="actions"><button type="button" id="client-secret-read" class="button secondary">'+h('Read secret')+'</button><button type="button" id="client-secret-rotate" class="button secondary">'+h('Rotate secret')+'</button><button type="button" id="client-secret-hide" class="button secondary">'+h('Hide')+'</button></div></section>':''}
  </form></div>`);
  const by=id=>document.getElementById(id), result=by('client-result'); let pending=false,secret='';
  const busy=v=>document.querySelectorAll('#client-form input, #client-form select, #client-form textarea, #client-form button').forEach(x=>x.disabled=v);
  const setSecret=v=>{secret=v||'';const out=by('client-secret');if(out)out.textContent=secret||t('Secret is hidden.')};
  const setPreset=device=>{by('client-confidential').checked=!device;by('client-redirects').value=device?'':by('client-redirects').value;by('client-scopes').value=(device?clientDeviceScopes:clientWebScopes.concat(['offline_access'])).join('\n');by('client-default-scopes').value=(device?clientDeviceScopes:['openid']).join('\n');document.querySelectorAll('[data-client-flow]').forEach(x=>x.checked=(device?[clientDeviceFlow,clientRefreshFlow]:[clientWebFlow,clientRefreshFlow]).includes(x.dataset.clientFlow));};
  by('client-web').onclick=()=>setPreset(false);by('client-device').onclick=()=>setPreset(true);
  if(editing&&confidential){by('client-secret-hide').onclick=()=>setSecret('');by('client-secret-read').onclick=async()=>{if(pending)return;setSecret('');pending=true;busy(true);try{const j=await api('/auth/v1/clients/'+encodeURIComponent(id)+'/secret',{method:'POST',body:''});setSecret(typeof j==='string'?j:j.secret)}catch(e){setSecret('');result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}};by('client-secret-rotate').onclick=async()=>{if(pending)return;setSecret('');pending=true;busy(true);try{const j=await api('/auth/v1/clients/'+encodeURIComponent(id)+'/secret',{method:'PUT',body:'',headers:{'If-Match':'"'+c.revision+'"'}});const etag=j._headers?.get?.('ETag')?.replaceAll('"',''),revision=Number(etag||j.revision||0);if(!revision)throw Error(t('Secret rotated, but the new revision was not returned; reload before making another change.'));c.revision=revision;setSecret(typeof j==='string'?j:j.secret)}catch(e){setSecret('');result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}}}
  by('client-form').onsubmit=async e=>{e.preventDefault();if(pending)return;const confidential=by('client-confidential').checked,redirects=clientRedirects(by('client-redirects').value),audience=clientRedirects(by('client-audience').value),scopes=clientValues(by('client-scopes').value),defaults=clientValues(by('client-default-scopes').value),enabledFlows=[...document.querySelectorAll('[data-client-flow]:checked')].map(x=>x.dataset.clientFlow),forceMfa=by('client-force-mfa').checked;if(!enabledFlows.length){result.className='error';result.textContent=t('Select at least one grant flow.');return}if(!confidential&&enabledFlows.includes(clientCredentialsFlow)){result.className='error';result.textContent=t('Public clients cannot use client credentials.');return}if(enabledFlows.includes(clientWebFlow)&&!redirects.length){result.className='error';result.textContent=t('Authorization code clients need a redirect URI.');return}const body={name:by('client-name').value||null,confidential,redirect_uris:redirects,audience,scopes,default_scopes:defaults,enabled_flows:enabledFlows,force_mfa:forceMfa};if(editing){body.enabled=by('client-enabled').checked;body.backchannel_logout_uri=c.backchannel_logout_uri??null;body.restrict_group_prefix=c.restrict_group_prefix??null}else body.id=by('client-id').value;
  setSecret('');pending=true;busy(true);try{const out=await api('/auth/v1/clients'+(editing?'/'+encodeURIComponent(id):''),{method:editing?'PUT':'POST',body:JSON.stringify(body),headers:editing?{'If-Match':'"'+c.revision+'"'}:{}});result.className='success';result.textContent=t('Saved');if(!editing)location.href='/auth/v1/admin/clients/'+encodeURIComponent(body.id)+'/edit';else{const etag=out._headers?.get?.('ETag')?.replaceAll('"','');c.revision=Number(etag||out.revision||0)||c.revision;await clients(id,'edit')}}catch(err){setSecret('');result.className='error';result.textContent=String(err.message).startsWith('409')?t('Conflict — reload to review the latest client; your form is preserved.'):err.message}finally{pending=false;busy(false)}};
  if(editing)by('client-delete').onclick=async()=>{if(pending||!confirm(t('Delete client {id} permanently?',{id})))return;setSecret('');pending=true;busy(true);try{await api('/auth/v1/clients/'+encodeURIComponent(id),{method:'DELETE',body:'',headers:{'If-Match':'"'+c.revision+'"'}});location.href='/auth/v1/admin/clients'}catch(e){result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}};
}
async function clients(id,mode){
  const t=globalThis.GoAuthyI18n?.t||((key,values={})=>String(key).replace(/\{(\w+)\}/g,(match,name)=>Object.hasOwn(values,name)?String(values[name]):match)),h=(key,values)=>esc(t(key,values));
  if(!id){shell(t('Clients'),t('Manage OAuth clients registered for this service.'),'<div class="toolbar"><span id="client-status" class="hint">'+h('Loading…')+'</span><a class="button" href="/auth/v1/admin/clients/new">'+h('New client')+'</a></div><div id="client-list"></div>');try{const rows=await api('/auth/v1/clients');document.getElementById('client-status').textContent=t('{count} clients',{count:rows.length});document.getElementById('client-list').innerHTML=rows.length?`<table><thead><tr><th>${h('Name')}</th><th>${h('Client ID')}</th><th>${h('Type')}</th><th>${h('Status')}</th><th>${h('Login appearance')}</th></tr></thead><tbody>${rows.map(x=>`<tr><td><a href="/auth/v1/admin/clients/${encodeURIComponent(x.id)}/edit">${esc(x.name||x.id)}</a></td><td>${esc(x.id)}</td><td>${h(x.confidential?'Confidential':'Public')}</td><td>${h(x.enabled?'Enabled':'Disabled')}</td><td><a href="/auth/v1/admin/clients/${encodeURIComponent(x.id)}/theme">${h('Customize')}</a></td></tr>`).join('')}</tbody></table>`:'<p class="state">'+h('No managed clients yet.')+'</p>'}catch(e){document.getElementById('client-list').innerHTML='<p class="error">'+esc(e.message)+'</p>'}return}
  if(mode==='new')return clientForm('',{},false,t);
  try{const c=await api('/auth/v1/clients/'+encodeURIComponent(id));return clientForm(id,c,true,t)}catch(e){shell(t('Client unavailable'),'',`<p class="error">${esc(e.message)}</p><p><a class="button secondary" href="/auth/v1/admin/clients">${h('Back to clients')}</a></p>`)}
}
