// Authentication collection definitions and user-owned draft connections.
// admin.js supplies api, shell, and esc; this module owns only its screen.
const collectionsEndpoint = '/auth/v1/auth-collections';
function collections(id, mode) {
  const endpoint = collectionsEndpoint;
  if (mode === 'new' || (id === 'new' && mode !== 'edit')) return collectionForm(null);
  if (id !== undefined) return api(endpoint + '/' + encodeURIComponent(id)).then(item => collectionForm(item)).catch(error => collectionError(error));
  shell('Authentication collections', 'Define metadata-only login shapes. Draft connections never store credentials or activate a SaaS connection.', '<div class="toolbar"><span class="hint" id="collection-status">Loading…</span><a class="button" href="/auth/v1/admin/collections/new">New collection</a></div><div id="collection-list" aria-live="polite"></div>');
  return api(endpoint).then(rows => {
    const list = Array.isArray(rows) ? rows : [];
    document.getElementById('collection-status').textContent = `${list.length} collection${list.length === 1 ? '' : 's'}`;
    document.getElementById('collection-list').innerHTML = list.length ? `<table><thead><tr><th>Name</th><th>ID</th><th>Method</th><th>Status</th><th>Revision</th></tr></thead><tbody>${list.map(x => `<tr><td><a href="/auth/v1/admin/collections/${encodeURIComponent(x.id)}/edit">${esc(x.name)}</a></td><td>${esc(x.id)}</td><td>${esc(x.auth_method)}</td><td>${x.enabled ? 'Enabled' : 'Disabled'}</td><td>${esc(x.revision)}</td></tr>`).join('')}</tbody></table>` : '<p class="state">No collections yet. Create the first definition above.</p>';
  }).catch(error => { document.getElementById('collection-list').innerHTML = `<p class="error">Could not load collections: ${esc(error.message)}</p>`; });
}

function collectionError(error) { shell('Collection unavailable', 'The requested definition could not be loaded.', `<p class="error" id="collection-error">${esc(error.message)}</p><p><a class="button secondary" href="/auth/v1/admin/collections">Back to collections</a></p>`); }
function providerIDs(raw) { const values = String(raw || '').split(/\r?\n/).map(x => x.trim()).filter(Boolean); if (values.length > 32 || values.some(x => !/^[a-z0-9][a-z0-9_-]{0,63}$/.test(x)) || new Set(values).size !== values.length) throw Error('Provider IDs must be unique lowercase IDs (up to 32).'); return values; }
function collectionFields(fields) { return (fields || []).map((f, i) => `<fieldset class="collection-field" data-field="${i}"><legend>Field ${i + 1}</legend><div class="checks"><label>Name<input data-field-name value="${esc(f.name)}" required pattern="[A-Za-z][A-Za-z0-9_.-]{0,63}"></label><label>Type<select data-field-type><option${f.type === 'string' ? ' selected' : ''}>string</option><option${f.type === 'boolean' ? ' selected' : ''}>boolean</option><option${f.type === 'integer' ? ' selected' : ''}>integer</option><option${f.type === 'enum' ? ' selected' : ''}>enum</option></select></label><label class="checks"><input type="checkbox" data-field-required${f.required ? ' checked' : ''}> Required</label><label>Max length<input data-field-max type="number" min="0" max="4096" value="${f.max_length ? esc(f.max_length) : ''}"></label></div><label>Options <span class="hint">JSON array of strings, e.g. ["one", "two"]; used for enum fields</span><textarea data-field-options rows="3">${esc(JSON.stringify(f.options || []))}</textarea><button type="button" class="button secondary" data-remove-field>Remove field</button></fieldset>`).join(''); }
function collectionForm(current) {
  const edit = !!current, id = current ? current.id : '';
  shell(`${edit ? 'Edit' : 'New'} authentication collection`, edit ? `Update ${esc(current.name)} without changing its ID. Revision ${esc(current.revision)} is protected by If-Match.` : 'Create a reusable definition for metadata-only draft connections.', `<div class="panel"><p class="hint">Draft foundation only: this stores metadata, not credentials, or provider activation.</p><form id="collection-form"><label for="collection-id">ID<input id="collection-id" required pattern="[A-Za-z0-9][A-Za-z0-9._-]{1,127}" value="${esc(id)}"${edit ? ' readonly' : ''}></label><label for="collection-name">Name<input id="collection-name" required maxlength="128" value="${esc(current?.name)}"></label><label for="collection-method">Authentication method<select id="collection-method"><option value="oauth2"${current?.auth_method === 'oauth2' ? ' selected' : ''}>OAuth 2</option><option value="api_key"${current?.auth_method === 'api_key' ? ' selected' : ''}>API key</option><option value="device_flow"${current?.auth_method === 'device_flow' ? ' selected' : ''}>Device flow</option></select></label><label for="collection-providers">Provider IDs <span class="hint">One ID per line. Empty OAuth denies providers; empty API key uses encrypted legacy storage without a connector. Removing an ID permanently revokes existing connections.</span><textarea id="collection-providers" rows="4">${esc((current?.provider_ids || []).join('\n'))}</textarea></label><label class="checks"><input id="collection-enabled" type="checkbox"${!edit || current.enabled ? ' checked' : ''}> Enabled</label><div><h2>Metadata fields</h2><div id="collection-fields">${collectionFields(current?.fields)}</div><button type="button" class="button secondary" id="add-collection-field">Add field</button></div><div class="actions"><button id="collection-save">${edit ? 'Save changes' : 'Create collection'}</button><a class="button secondary" href="/auth/v1/admin/collections">Cancel</a>${edit ? '<button type="button" class="button secondary" id="collection-delete">Delete collection</button>' : ''}<span id="collection-result" role="status"></span></div></form></div>`);
  const form = document.getElementById('collection-form'), result = document.getElementById('collection-result'), fields = document.getElementById('collection-fields'); let pending = false;
  const renumber = () => fields.querySelectorAll('.collection-field').forEach((row, i) => { const legend = row.querySelector('legend'); if (legend) legend.textContent = `Field ${i + 1}`; });
  const syncMax = () => fields.querySelectorAll('.collection-field').forEach(row => { const type = row.querySelector('[data-field-type]'), max = row.querySelector('[data-field-max]'); if (!type || !max) return; max.disabled = type.value !== 'string'; if (max.disabled) max.value = ''; });
  document.getElementById('add-collection-field').onclick = () => { if (fields.querySelectorAll('.collection-field').length >= 32) return; fields.insertAdjacentHTML('beforeend', collectionFields([{name: '', type: 'string', required: false, max_length: 0, options: []}])); renumber(); syncMax(); fields.lastElementChild.querySelector('[data-field-name]').focus(); };
  fields.onclick = e => { if (e.target.matches('[data-remove-field]')) { e.target.closest('.collection-field').remove(); renumber(); } };
  fields.onchange = e => { if (e.target.matches('[data-field-type]')) syncMax(); };
  renumber(); syncMax();
  const busy = on => { form.querySelectorAll('input,select,textarea,button').forEach(control => { control.disabled = on || (edit && control.id === 'collection-id'); }); if (!on) syncMax(); };
  form.onsubmit = async e => { e.preventDefault(); if (pending) return; pending = true; busy(true); result.className = ''; result.textContent = 'Saving…'; try {
    const outFields = [...fields.querySelectorAll('.collection-field')].map(row => { const type = row.querySelector('[data-field-type]').value, max = row.querySelector('[data-field-max]').value; return {name: row.querySelector('[data-field-name]').value, type, required: row.querySelector('[data-field-required]').checked, ...(type === 'string' && max ? {max_length: Number(max)} : {}), ...(type === 'enum' ? {options: JSON.parse(row.querySelector('[data-field-options]').value)} : {})}; });
    const ids = providerIDs(document.getElementById('collection-providers').value), method = document.getElementById('collection-method').value; if (method === 'api_key' && ids.length > 1) throw Error('API key collections allow at most one provider ID.'); if (method === 'device_flow' && ids.length) throw Error('Device flow collections cannot define provider IDs.'); if (edit && (current.auth_method === 'oauth2' || current.auth_method === 'api_key') && (current.provider_ids || []).some(x => !ids.includes(x)) && !confirm('Removing provider IDs permanently revokes existing connections. Continue?')) { pending = false; busy(false); result.textContent = 'Save cancelled'; return; }
    const body = {id: document.getElementById('collection-id').value, name: document.getElementById('collection-name').value, auth_method: document.getElementById('collection-method').value, enabled: document.getElementById('collection-enabled').checked, provider_ids: ids, fields: outFields};
    const {id: _id, ...updateBody} = body, opts = {method: edit ? 'PUT' : 'POST', body: JSON.stringify(edit ? updateBody : body)};
    if (edit) opts.headers = {'If-Match': `"${current.revision}"`};
    await api(edit ? collectionsEndpoint + '/' + encodeURIComponent(id) : collectionsEndpoint, opts); result.className = 'success'; result.textContent = 'Saved'; await collections();
  } catch (error) { result.className = 'error'; result.textContent = error.message + (error.message.includes('409') || error.message.toLowerCase().includes('conflict') ? ' Reload the collection before trying again.' : ''); } finally { pending = false; busy(false); }
  };
  if (edit) document.getElementById('collection-delete').onclick = async () => { if (pending || !confirm(`Delete collection ${current.name} permanently?`)) return; pending = true; busy(true); result.textContent = 'Deleting…'; try { await api(collectionsEndpoint + '/' + encodeURIComponent(id), {method: 'DELETE', headers: {'If-Match': `"${current.revision}"`}}); await collections(); } catch (error) { result.className = 'error'; result.textContent = error.message + (error.message.includes('409') || error.message.toLowerCase().includes('conflict') ? ' Reload the collection before trying again.' : ''); pending = false; busy(false); } };
}
