const providerKinds=['oauth2','api_key'];
const providerScopes=v=>(v||[]).join('\n');
function providerForm(id,current={},editing=false){
  const p=current||{},kind=p.kind||'oauth2',scopes=p.scopes||[],isOAuth=kind==='oauth2';
  shell(`${editing?'Edit':'New'} provider`,editing?`Update ${esc(p.name||id)} and preserve its immutable ID.`:'Register a managed upstream identity provider.',`<div class="panel"><form id="provider-form">
    <label for="prov-id">Provider ID<input id="prov-id" required pattern="[a-z0-9_-]{1,64}" value="${esc(id||'')}" ${editing?'readonly':''}></label>
    <label for="prov-name">Name<input id="prov-name" required value="${esc(p.name||'')}"></label>
    <label for="prov-kind">Kind<select id="prov-kind">${providerKinds.map(k=>`<option value="${k}"${k===kind?' selected':''}>${k}</option>`).join('')}</select></label>
    <div id="prov-oauth-fields"${isOAuth?'':' style="display:none"'}">
      <label for="prov-callback">Callback URI<input id="prov-callback" type="url" value="${esc(p.callback_uri||'')}"></label>
      <label for="prov-client-id">Client ID<input id="prov-client-id" value="${esc(p.client_id||'')}"></label>
      <label for="prov-secret">${editing?'New secret <span class="hint">Leave blank to keep current</span>':'Client secret'}<input id="prov-secret" type="password" autocomplete="new-password"></label>
      <label for="prov-auth-endpoint">Authorization endpoint<input id="prov-auth-endpoint" type="url" value="${esc(p.auth_endpoint||'')}"></label>
      <label for="prov-token-endpoint">Token endpoint<input id="prov-token-endpoint" type="url" value="${esc(p.token_endpoint||'')}"></label>
      <label for="prov-scopes">Scopes <span class="hint">One per line</span><textarea id="prov-scopes">${esc(providerScopes(scopes))}</textarea></label>
      <label for="prov-auth-style">Auth style<select id="prov-auth-style"><option value="header"${p.auth_style!=='params'?' selected':''}>HTTP Basic (header)</option><option value="params"${p.auth_style==='params'?' selected':''}>Form POST (params)</option></select></label>
      <label for="prov-identity">Identity endpoint <span class="hint">Optional userinfo URL</span><input id="prov-identity" type="url" value="${esc(p.identity_endpoint||'')}"></label>
      <label for="prov-subject">Subject field <span class="hint">JSON claim path for user ID</span><input id="prov-subject" value="${esc(p.subject_field||'')}"></label>
    </div>
    ${editing?`<label class="checks"><span><input id="prov-enabled" type="checkbox" ${p.enabled?'checked':''}> Enabled</span></label>`:''}
    <div class="actions"><button type="submit">${editing?'Save changes':'Create provider'}</button><a class="button secondary" href="/auth/v1/admin/providers">Cancel</a>${editing?'<button type="button" id="prov-delete" class="button secondary">Delete</button>':''}<span id="prov-result" role="status"></span></div>
  </form></div>`);
  const by=id=>document.getElementById(id),result=by('prov-result');let pending=false;
  const busy=v=>document.querySelectorAll('#provider-form button').forEach(x=>x.disabled=v);
  by('prov-kind').onchange=()=>{const show=by('prov-kind').value==='oauth2';by('prov-oauth-fields').style.display=show?'':'none'};
  by('provider-form').onsubmit=async e=>{e.preventDefault();if(pending)return;const kind=by('prov-kind').value,body={name:by('prov-name').value,kind,enabled:editing?by('prov-enabled').checked:true};if(kind==='oauth2'){body.callback_uri=by('prov-callback').value;body.client_id=by('prov-client-id').value;const secret=by('prov-secret').value;if(secret)body.client_secret=secret;body.auth_endpoint=by('prov-auth-endpoint').value;body.token_endpoint=by('prov-token-endpoint').value;const scopes=String(by('prov-scopes').value).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(scopes.length)body.scopes=scopes;body.auth_style=by('prov-auth-style').value;const identity=by('prov-identity').value.trim();if(identity)body.identity_endpoint=identity;const subject=by('prov-subject').value.trim();if(subject)body.subject_field=subject;if(!editing)body.id=by('prov-id').value}
    pending=true;busy(true);try{await api('/auth/v1/saas/providers'+(editing?'/'+encodeURIComponent(id):''),{method:editing?'PUT':'POST',body:JSON.stringify(body),headers:editing?{'If-Match':'"'+p.revision+'"'}:{}});result.className='success';result.textContent='Saved';if(!editing)location.href='/auth/v1/admin/providers/'+encodeURIComponent(body.id)+'/edit';else await providers(id,'edit')}catch(err){result.className='error';result.textContent=String(err.message).startsWith('409')?'Conflict — reload to review the latest provider; your form is preserved.':err.message}finally{pending=false;busy(false)}};
  if(editing)by('prov-delete').onclick=async()=>{if(pending||!confirm('Delete provider '+id+' permanently?'))return;pending=true;busy(true);try{await api('/auth/v1/saas/providers/'+encodeURIComponent(id),{method:'DELETE',body:'',headers:{'If-Match':'"'+p.revision+'"'}});location.href='/auth/v1/admin/providers'}catch(e){result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}}}
async function providers(id,mode){if(!id){shell('Providers','Manage upstream identity providers for SaaS account connections.','<div class="toolbar"><span id="prov-status" class="hint">Loading…</span><a class="button" href="/auth/v1/admin/providers/new">New provider</a></div><div id="prov-list"></div>');try{const rows=await api('/auth/v1/saas/providers');const list=Array.isArray(rows)?rows:[];document.getElementById('prov-status').textContent=list.length+' providers';document.getElementById('prov-list').innerHTML=list.length?`<table><thead><tr><th>Name</th><th>Kind</th><th>Callback URI</th><th>Status</th><th>Actions</th></tr></thead><tbody>${list.map(x=>`<tr><td><a href="/auth/v1/admin/providers/${encodeURIComponent(x.id)}/edit">${esc(x.name||x.id)}</a></td><td>${esc(x.kind)}</td><td>${esc(x.callback_uri||'—')}</td><td>${x.enabled?'Enabled':'Disabled'}</td><td><a href="/auth/v1/admin/providers/${encodeURIComponent(x.id)}/edit">Edit</a></td></tr>`).join('')}</tbody></table>`:'<p class="state">No providers configured yet. Create the first one above.</p>'}catch(e){document.getElementById('prov-list').innerHTML='<p class="error">'+esc(e.message)+'</p>'}return}if(mode==='new'){return providerForm('',{},false)}try{const p=await api('/auth/v1/saas/providers/'+encodeURIComponent(id));return providerForm(id,p,true)}catch(e){shell('Provider unavailable','',`<p class="error">${esc(e.message)}</p>`)}}
