const providerKinds=['oauth2','api_key'];
const providerScopes=v=>(v||[]).join('\n');
function providerForm(id,current={},editing=false,t=(key,values={})=>String(key).replace(/\{(\w+)\}/g,(match,name)=>Object.hasOwn(values,name)?String(values[name]):match)){
  const h=(key,values)=>esc(t(key,values));
  const p=current||{},kind=p.kind||'oauth2',scopes=p.scopes||[],isOAuth=kind==='oauth2';
  shell(t(editing?'Edit provider':'New provider'),editing?t('Update {name} and preserve its immutable ID.',{name:esc(p.name||id)}):t('Register a managed upstream identity provider.'),`<div class="panel"><form id="provider-form">
    <label for="prov-id">${h('Provider ID')}<input id="prov-id" required pattern="[a-z0-9_-]{1,64}" value="${esc(id||'')}" ${editing?'readonly':''}></label>
    <label for="prov-name">${h('Name')}<input id="prov-name" required value="${esc(p.name||'')}"></label>
    <label for="prov-kind">${h('Kind')}<select id="prov-kind">${providerKinds.map(k=>`<option value="${k}"${k===kind?' selected':''}>${h(k==='oauth2'?'OAuth 2':'API key')}</option>`).join('')}</select></label>
    <div id="prov-oauth-fields"${isOAuth?'':' hidden'}>
      <label for="prov-callback">${h('Callback URI')}<input id="prov-callback" type="url" value="${esc(p.callback_uri||'')}"></label>
      <label for="prov-client-id">${h('Client ID')}<input id="prov-client-id" value="${esc(p.client_id||'')}"></label>
      <label for="prov-secret">${editing?h('New secret')+' <span class="hint">'+h('Leave blank to keep current')+'</span>':h('Client secret')}<input id="prov-secret" type="password" autocomplete="new-password"></label>
      <label for="prov-auth-endpoint">${h('Authorization endpoint')}<input id="prov-auth-endpoint" type="url" value="${esc(p.auth_endpoint||'')}"></label>
      <label for="prov-token-endpoint">${h('Token endpoint')}<input id="prov-token-endpoint" type="url" value="${esc(p.token_endpoint||'')}"></label>
      <label for="prov-scopes">${h('Scopes')} <span class="hint">${h('One per line')}</span><textarea id="prov-scopes">${esc(providerScopes(scopes))}</textarea></label>
      <label for="prov-auth-style">${h('Auth style')}<select id="prov-auth-style"><option value="header"${p.auth_style!=='params'?' selected':''}>${h('HTTP Basic (header)')}</option><option value="params"${p.auth_style==='params'?' selected':''}>${h('Form POST (params)')}</option></select></label>
      <label for="prov-identity">${h('Identity endpoint')} <span class="hint">${h('Optional userinfo URL')}</span><input id="prov-identity" type="url" value="${esc(p.identity_endpoint||'')}"></label>
      <label for="prov-subject">${h('Subject field')} <span class="hint">${h('JSON claim path for user ID')}</span><input id="prov-subject" value="${esc(p.subject_field||'')}"></label>
    </div>
    <div id="prov-api-key-fields"${kind==='api_key'?'':' hidden'}><label for="prov-connector">${h('API key connector configuration (JSON)')}<textarea id="prov-connector" rows="12">${esc(p.connector?JSON.stringify(p.connector,null,2):'')}</textarea></label><p class="hint">${h('Set id, header, prefix, and operations with each operation’s HTTPS URL and response_fields. The connector id must match the provider id.')}</p></div>
    ${editing?`<label class="checks"><span><input id="prov-enabled" type="checkbox" ${p.enabled?'checked':''}> ${h('Enabled')}</span></label>`:''}
    <div class="actions"><button type="submit">${h(editing?'Save changes':'Create provider')}</button><a class="button secondary" href="/auth/v1/admin/providers">${h('Cancel')}</a>${editing?'<button type="button" id="prov-delete" class="button secondary">'+h('Delete')+'</button>':''}<span id="prov-result" role="status"></span></div>
  </form></div>`);
  const by=id=>document.getElementById(id),result=by('prov-result');let pending=false;
  const busy=v=>document.querySelectorAll('#provider-form input, #provider-form select, #provider-form textarea, #provider-form button').forEach(x=>x.disabled=v);
  by('prov-kind').onchange=()=>{const show=by('prov-kind').value==='oauth2';by('prov-oauth-fields').hidden=!show;by('prov-api-key-fields').hidden=show?true:by('prov-kind').value!=='api_key'};
  by('provider-form').onsubmit=async e=>{e.preventDefault();if(pending)return;const kind=by('prov-kind').value,body={name:by('prov-name').value,kind,enabled:editing?by('prov-enabled').checked:true};if(kind==='oauth2'){body.callback_uri=by('prov-callback').value;body.client_id=by('prov-client-id').value;const secret=by('prov-secret').value;if(secret)body.client_secret=secret;body.auth_endpoint=by('prov-auth-endpoint').value;body.token_endpoint=by('prov-token-endpoint').value;const scopes=String(by('prov-scopes').value).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(scopes.length)body.scopes=scopes;body.auth_style=by('prov-auth-style').value;const identity=by('prov-identity').value.trim();if(identity)body.identity_endpoint=identity;const subject=by('prov-subject').value.trim();if(subject)body.subject_field=subject}else if(kind==='api_key'){try{body.connector=JSON.parse(by('prov-connector').value)}catch{result.className='error';result.textContent=t('Connector configuration must be valid JSON.');return}}if(!editing)body.id=by('prov-id').value;
    pending=true;busy(true);try{await api('/auth/v1/saas/providers'+(editing?'/'+encodeURIComponent(id):''),{method:editing?'PUT':'POST',body:JSON.stringify(body),headers:editing?{'If-Match':'"'+p.revision+'"'}:{}});result.className='success';result.textContent=t('Saved');if(!editing)location.href='/auth/v1/admin/providers/'+encodeURIComponent(body.id)+'/edit';else await providers(id,'edit')}catch(err){result.className='error';result.textContent=String(err.message).startsWith('409')?t('Conflict — reload to review the latest provider; your form is preserved.'):err.message}finally{pending=false;busy(false)}};
  if(editing)by('prov-delete').onclick=async()=>{if(pending||!confirm(t('Delete provider {id} permanently?',{id})))return;pending=true;busy(true);try{await api('/auth/v1/saas/providers/'+encodeURIComponent(id),{method:'DELETE',body:'',headers:{'If-Match':'"'+p.revision+'"'}});location.href='/auth/v1/admin/providers'}catch(e){result.className='error';result.textContent=e.message}finally{pending=false;busy(false)}}}
async function providers(id,mode){
  const t=globalThis.GoAuthyI18n?.t||((key,values={})=>String(key).replace(/\{(\w+)\}/g,(match,name)=>Object.hasOwn(values,name)?String(values[name]):match)),h=(key,values)=>esc(t(key,values));
  if(!id){shell(t('Providers'),t('Manage upstream identity providers for SaaS account connections.'),'<div class="toolbar"><span id="prov-status" class="hint">'+h('Loading…')+'</span><a class="button" href="/auth/v1/admin/providers/new">'+h('New provider')+'</a></div><div id="prov-list"></div>');try{const rows=await api('/auth/v1/saas/providers'),list=Array.isArray(rows)?rows:[];document.getElementById('prov-status').textContent=t('{count} providers',{count:list.length});document.getElementById('prov-list').innerHTML=list.length?`<table><thead><tr><th>${h('Name')}</th><th>${h('Kind')}</th><th>${h('Callback URI')}</th><th>${h('Status')}</th><th>${h('Actions')}</th></tr></thead><tbody>${list.map(x=>`<tr><td><a href="/auth/v1/admin/providers/${encodeURIComponent(x.id)}/edit">${esc(x.name||x.id)}</a></td><td>${h(x.kind==='oauth2'?'OAuth 2':x.kind==='api_key'?'API key':x.kind)}</td><td>${esc(x.callback_uri||'—')}</td><td>${h(x.enabled?'Enabled':'Disabled')}</td><td><a href="/auth/v1/admin/providers/${encodeURIComponent(x.id)}/edit">${h('Edit')}</a></td></tr>`).join('')}</tbody></table>`:'<p class="state">'+h('No providers configured yet. Create the first one above.')+'</p>'}catch(e){document.getElementById('prov-list').innerHTML='<p class="error">'+esc(e.message)+'</p>'}return}
  if(mode==='new')return providerForm('',{},false,t);
  try{const p=await api('/auth/v1/saas/providers/'+encodeURIComponent(id));return providerForm(id,p,true,t)}catch(e){shell(t('Provider unavailable'),'',`<p class="error">${esc(e.message)}</p><p><a class="button secondary" href="/auth/v1/admin/providers">${h('Back to providers')}</a></p>`)}
}
