apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goauthy
  namespace: goauthy
spec:
  template:
    spec:
      containers:
        - name: goauthy
          env:
            - name: GOAUTHY_BOOTSTRAP_ALLOWED_RESOURCES
              value: '["https://api.example.test/v1","https://resource.example.test/v1"]'
            - name: GOAUTHY_BOOTSTRAP_DEFAULT_AUD
              value: https://api.example.test/v1
