(() => {
  'use strict';
  const i18n = globalThis.GoAuthyI18n;
  if (!i18n?.messages) return;
  Object.assign(i18n.messages, {
    'Account': '계정', 'Skip to account settings': '계정 설정으로 건너뛰기', 'Account settings': '계정 설정', 'Back to dashboard': '대시보드로 돌아가기', 'Sign out': '로그아웃', 'Language': '언어', 'Account sections': '계정 섹션', 'Overview': '개요', 'Security': '보안', 'Passkeys': '패스키', 'Connections': '연결', 'Devices': '기기', 'Profile': '프로필', 'Loading your account…': '계정을 불러오는 중…', 'Preferred username': '기본 사용자 이름', 'Username': '사용자 이름', 'Use the username rules configured by this service.': '이 서비스에 설정된 사용자 이름 규칙을 따르세요.', 'Save username': '사용자 이름 저장', 'Change password': '비밀번호 변경', 'Current password': '현재 비밀번호', 'New password': '새 비밀번호', 'Confirm new password': '새 비밀번호 확인', 'Personal details': '개인 정보', 'Save details': '정보 저장', 'Your browser does not support passkeys.': '브라우저가 패스키를 지원하지 않습니다.', 'New passkey name': '새 패스키 이름', 'Add passkey': '패스키 추가', 'Passwordless sign-in': '비밀번호 없는 로그인', 'Turn off password sign-in': '비밀번호 로그인 끄기', 'Restore password sign-in': '비밀번호 로그인 복원', 'My connections': '내 연결', 'Keep tokens and passwords out of metadata fields. For API-key collections, save a connection first, then use Manage API key for encrypted storage. Manage service access separately to authorize a consumer\'s registered operations.': '메타데이터 필드에 토큰과 비밀번호를 넣지 마세요. API 키 컬렉션은 먼저 연결을 저장한 뒤 API 키 관리에서 암호화해 저장하세요. 소비자의 등록된 작업 권한은 서비스 액세스에서 별도로 관리하세요.', 'Refresh collections': '컬렉션 새로고침', 'Collection': '컬렉션', 'Save connection': '연결 저장', 'Cancel edit': '편집 취소', 'Authorized devices': '승인된 기기', 'Review and revoke device authorizations. Device names, location, and last-used details are not available.': '기기 승인을 검토하고 취소하세요. 기기 이름, 위치 및 마지막 사용 정보는 제공되지 않습니다.', 'Refresh devices': '기기 새로고침', 'Delete account': '계정 삭제', 'This permanently deletes your account.': '계정이 영구적으로 삭제됩니다.', 'Type your email to confirm': '확인을 위해 이메일을 입력하세요', 'Delete my account': '내 계정 삭제',
    'Your session has expired. Sign in again.': '세션이 만료되었습니다. 다시 로그인하세요.', 'Request failed ({{status}}).': '요청에 실패했습니다 ({{status}}).', 'Your profile': '내 프로필', 'Email address is not verified.': '이메일 주소가 확인되지 않았습니다.', 'This requires an enrolled passkey and will remove password sign-in.': '등록된 패스키가 필요하며 비밀번호 로그인이 제거됩니다.', 'Use a registered passkey to sign in again before converting.': '변경하기 전에 등록된 패스키로 다시 로그인하세요.', 'Turn off password sign-in for this account?': '이 계정의 비밀번호 로그인을 끄시겠습니까?', 'Password sign-in disabled.': '비밀번호 로그인이 비활성화되었습니다.', 'Passwords do not match.': '비밀번호가 일치하지 않습니다.', 'Passkeys are unavailable in this browser.': '이 브라우저에서는 패스키를 사용할 수 없습니다.', 'Passkey authorization cancelled.': '패스키 인증이 취소되었습니다.', 'This browser cannot serialize passkey credentials.': '이 브라우저에서는 패스키 자격 증명을 직렬화할 수 없습니다.', 'Password sign-in restored.': '비밀번호 로그인이 복원되었습니다.', 'Delete your account permanently?': '계정을 영구적으로 삭제하시겠습니까?', 'Account deletion was not completed ({{status}}).': '계정 삭제가 완료되지 않았습니다 ({{status}}).', 'Account deleted': '계정이 삭제되었습니다.', 'No passkeys registered.': '등록된 패스키가 없습니다.', 'Remove': '삭제', 'Waiting for passkey verification…': '패스키 확인을 기다리는 중…'
  });
  Object.assign(i18n.messages, {
    'Home': '홈', 'Passkeys are still loading. Try again.': '패스키를 불러오는 중입니다. 다시 시도하세요.', 'Enter your current password.': '현재 비밀번호를 입력하세요.', 'Enter a name for this passkey.': '이 패스키의 이름을 입력하세요.', 'Passkey added.': '패스키가 추가되었습니다.', 'Remove passkey “{{name}}”?': '패스키 “{{name}}”을(를) 삭제하시겠습니까?', 'Passkey removed.': '패스키가 삭제되었습니다.', 'Unable to load passkeys.': '패스키를 불러올 수 없습니다.', 'Unable to load editable details.': '편집 가능한 정보를 불러올 수 없습니다.', 'Username saved.': '사용자 이름이 저장되었습니다.', 'New passwords do not match.': '새 비밀번호가 일치하지 않습니다.', 'Password changed. Use the new password the next time you sign in.': '비밀번호가 변경되었습니다. 다음 로그인부터 새 비밀번호를 사용하세요.', 'Reload the page to load your details before saving.': '저장하기 전에 페이지를 새로고침하여 정보를 불러오세요.', 'Enter valid JSON for structured details.': '구조화된 정보에는 올바른 JSON을 입력하세요.', 'Details saved.': '정보가 저장되었습니다.',
    'This browser cannot read the connection integer safely.': '이 브라우저에서는 연결 정수를 안전하게 읽을 수 없습니다.', 'Enter a valid integer for {{name}}.': '{{name}}에 올바른 정수를 입력하세요.', 'Enter a valid 64-bit integer for {{name}}.': '{{name}}에 올바른 64비트 정수를 입력하세요.', 'Choose a collection first.': '먼저 컬렉션을 선택하세요.', '{{name}} is required.': '{{name}}은(는) 필수입니다.', 'Not set': '설정 안 함', 'True': '참', 'False': '거짓', 'Create connection': '연결 만들기', 'No saved connections.': '저장된 연결이 없습니다.', 'draft': '초안', '{{id}} ({{state}})': '{{id}} ({{state}})', 'Edit': '편집', 'Delete': '삭제', 'This connection contains an integer outside the browser safe range; editing is disabled.': '이 연결에는 브라우저 안전 범위를 벗어난 정수가 있어 편집할 수 없습니다.', 'Manage API key': 'API 키 관리', 'API key': 'API 키', 'Save API key': 'API 키 저장', 'Revoke API key': 'API 키 취소', 'Cancel': '취소', 'Checking API key status…': 'API 키 상태를 확인하는 중…', 'API key registered. Saving a new key rotates it.': 'API 키가 등록되었습니다. 새 키를 저장하면 키가 교체됩니다.', 'API key revoked. It cannot be registered again.': 'API 키가 취소되었습니다. 다시 등록할 수 없습니다.', 'No API key registered.': '등록된 API 키가 없습니다.', 'Unable to load API key status.': 'API 키 상태를 불러올 수 없습니다.', 'This collection is disabled; new connections cannot be saved.': '이 컬렉션은 비활성화되어 새 연결을 저장할 수 없습니다.', 'Connection saved.': '연결이 저장되었습니다.', 'Connection created.': '연결이 만들어졌습니다.', 'This connection changed elsewhere. Reload and try again.': '이 연결이 다른 곳에서 변경되었습니다. 새로고침 후 다시 시도하세요.', 'Delete connection “{{id}}”?': '연결 “{{id}}”을(를) 삭제하시겠습니까?', 'Connection deleted.': '연결이 삭제되었습니다.',
    'No authorized devices.': '승인된 기기가 없습니다.', 'Device {{id}}': '기기 {{id}}', 'Client: {{client}} · Scopes: {{scopes}} · Created: {{created}}': '클라이언트: {{client}} · 범위: {{scopes}} · 생성: {{created}}', 'Revoked: {{timestamp}}': '취소됨: {{timestamp}}', 'Revoke device': '기기 취소', 'Revoke device {{id}} for client {{client}}?': '클라이언트 {{client}}의 기기 {{id}}을(를) 취소하시겠습니까?', 'Device revoked.': '기기가 취소되었습니다.',
    'This grant changed elsewhere. Close and reopen to reload it.': '이 권한이 다른 곳에서 변경되었습니다. 닫았다가 다시 열어 불러오세요.', 'Unable to complete that grant action.': '서비스 액세스 작업을 완료할 수 없습니다.', 'Manage service access': '서비스 액세스 관리', 'Service access': '서비스 액세스', 'Close': '닫기', 'Stored consent; current policy is checked on each use.': '저장된 동의이며, 사용할 때마다 현재 정책을 확인합니다.', 'Revoke access': '액세스 취소', 'No service access grants.': '서비스 액세스 권한이 없습니다.', 'Consumer client ID (admin supplied ID; the server validates it)': '소비자 클라이언트 ID (관리자가 제공하며 서버에서 확인)', 'Purpose': '용도', 'Expires': '만료', 'Create service access': '서비스 액세스 만들기'
  });
  Object.assign(i18n.messages, {
    'Request failed ({status}).': '요청에 실패했습니다 ({status}).',
    'Account deletion was not completed ({status}).': '계정 삭제가 완료되지 않았습니다 ({status}).',
    'Remove passkey “{name}”?': '패스키 “{name}”을(를) 삭제하시겠습니까?',
    'Enter a valid integer for {name}.': '{name}에 올바른 정수를 입력하세요.', 'Enter a valid 64-bit integer for {name}.': '{name}에 올바른 64비트 정수를 입력하세요.', '{name} is required.': '{name}은(는) 필수입니다.', '{id} ({state})': '{id} ({state})', 'Delete connection “{id}”?': '연결 “{id}”을(를) 삭제하시겠습니까?',
    'Device {id}': '기기 {id}', 'Client: {client} · Scopes: {scopes} · Created: {created}': '클라이언트: {client} · 범위: {scopes} · 생성: {created}', 'Revoked: {timestamp}': '취소됨: {timestamp}', 'Revoke device {id} for client {client}?': '클라이언트 {client}의 기기 {id}을(를) 취소하시겠습니까?',
    'Manage OAuth': 'OAuth 관리', 'Provider': '제공자', 'Start authorization': '인증 시작', 'Open provider authorization': '제공자 인증 열기', 'Check status': '상태 확인', 'Refresh access': '액세스 새로고침', 'Revoke locally': '로컬에서 취소', 'Prepare reconnect': '재연결 준비', ' Provider: {provider}.': ' 제공자: {provider}.', 'Authorization has not started.{provider}': '인증이 시작되지 않았습니다.{provider}', 'OAuth connection ready.{provider} Account: {account}. Scopes: {scopes}.': 'OAuth 연결이 준비되었습니다.{provider} 계정: {account}. 범위: {scopes}.', 'none': '없음', 'OAuth connection revoked locally. Provider tokens are unaffected. Prepare reconnect to authorize again.': 'OAuth 연결이 로컬에서 취소되었습니다. 제공자 토큰에는 영향이 없습니다. 다시 인증하려면 재연결을 준비하세요.', 'Reconnect is prepared. Start a new authorization.': '재연결이 준비되었습니다. 새 인증을 시작하세요.', 'The last exchange outcome is uncertain. Do not retry it. Check status, or revoke locally and reconnect.': '마지막 교환 결과가 확실하지 않습니다. 다시 시도하지 마세요. 상태를 확인하거나 로컬에서 취소한 뒤 재연결하세요.', 'OAuth refresh is in progress. Check status before any further action, or revoke locally.': 'OAuth 새로고침이 진행 중입니다. 다른 작업 전 상태를 확인하거나 로컬에서 취소하세요.', 'Checking OAuth status…': 'OAuth 상태를 확인하는 중…', 'Unable to load OAuth status. Check status to try again.': 'OAuth 상태를 불러올 수 없습니다. 상태 확인으로 다시 시도하세요.', 'Revoke this OAuth connection locally? Provider tokens are unaffected.': '이 OAuth 연결을 로컬에서 취소하시겠습니까? 제공자 토큰에는 영향이 없습니다.', 'Prepare this connection to reconnect? You will need to start authorization separately.': '이 연결을 재연결하도록 준비하시겠습니까? 인증은 별도로 시작해야 합니다.', 'Refresh access with the provider now? This sends one token exchange; an uncertain result must not be retried.': '지금 제공자에서 액세스를 새로고침하시겠습니까? 토큰 교환을 한 번 보내며 결과가 불확실하면 다시 시도하면 안 됩니다.', 'Open authorization in a new tab, return here, then check status.': '새 탭에서 인증을 열고 여기로 돌아와 상태를 확인하세요.', 'OAuth action failed. Check status before trying again.': 'OAuth 작업에 실패했습니다. 다시 시도하기 전에 상태를 확인하세요.'
  });
  Object.assign(i18n.messages, {
    'This API key changed elsewhere. Reload and try again.': '이 API 키가 다른 곳에서 변경되었습니다. 새로고침 후 다시 시도하세요.', 'Unable to manage this API key.': 'API 키를 관리할 수 없습니다.', 'Provider: {provider}\nKey header: {header} ({prefix})\nAllowed operations:\n{operations}\nSettings digest: {digest}': '제공자: {provider}\n키 헤더: {header} ({prefix})\n허용된 작업:\n{operations}\n설정 요약: {digest}', 'no prefix': '접두사 없음', 'Response fields:': '응답 필드:', 'Enter an API key up to 2048 characters.': '2048자 이하의 API 키를 입력하세요.', 'API key saved.': 'API 키가 저장되었습니다.', ' Close and reopen to review provider settings again.': ' 닫았다가 다시 열어 제공자 설정을 다시 검토하세요.', 'Revoke this API key locally? This only revokes it in GoAuthy; the provider key is unchanged.': '이 API 키를 로컬에서 취소하시겠습니까? GoAuthy에서만 취소되며 제공자 키는 변경되지 않습니다.', 'API key revoked locally. It cannot be registered again.': 'API 키가 로컬에서 취소되었습니다. 다시 등록할 수 없습니다.'
  });
  Object.assign(i18n.messages, {
    'Grant {id} · Consumer: {consumer} · Mode: {mode} · Purpose: {purpose} · Resource: {resource} · Expires: {expires} · {status}': '권한 {id} · 소비자: {consumer} · 방식: {mode} · 용도: {purpose} · 리소스: {resource} · 만료: {expires} · {status}', 'Revoked': '취소됨', 'Stored consent': '저장된 동의', 'Mode: credential delivery': '방식: 자격 증명 전달', 'Mode: proxy': '방식: 프록시', 'Allow refresh-token use for future deliveries': '향후 전달에 새로고침 토큰 사용 허용', 'I authorize this consumer to use all displayed operations until the expiry. No implicit consent is granted.': '이 소비자가 만료 시점까지 표시된 모든 작업을 사용하도록 허용합니다. 암묵적 동의는 부여되지 않습니다.', 'Warning: this service receives an access token and can use all granted scopes, without proxy operation or response-field restrictions. The purpose is descriptive, not an access restriction. Refresh delegation is optional: the service may ask GoAuthy to refresh, while GoAuthy keeps the refresh token and client secret. Revoking stops future fetches but cannot recall an already delivered token.': '경고: 이 서비스는 액세스 토큰을 받아 프록시 작업 또는 응답 필드 제한 없이 부여된 모든 범위를 사용할 수 있습니다. 용도는 설명일 뿐 접근 제한이 아닙니다. 새로고침 위임은 선택 사항입니다. 서비스는 GoAuthy에 새로고침을 요청할 수 있으며, GoAuthy는 새로고침 토큰과 클라이언트 시크릿을 보관합니다. 취소하면 이후 가져오기는 중지되지만 이미 전달된 토큰은 회수할 수 없습니다.', 'I authorize this consumer to receive access tokens for the displayed account and scopes until the consent expires.': '이 소비자가 동의 만료 시점까지 표시된 계정과 범위의 액세스 토큰을 받도록 허용합니다.', 'Enter a consumer client ID, a purpose up to 256 bytes, and a future expiry within 30 days.': '소비자 클라이언트 ID, 256바이트 이하의 용도 및 30일 이내의 미래 만료 시점을 입력하세요.', 'Service access created.': '서비스 액세스가 만들어졌습니다.', 'Creation is pending for this collection; existing service access can still be reviewed and revoked.': '이 컬렉션의 생성은 보류 중입니다. 기존 서비스 액세스는 계속 검토하고 취소할 수 있습니다.', 'Revoke service access for {consumer}? This cannot recall requests or credentials already delivered.': '{consumer}의 서비스 액세스를 취소하시겠습니까? 이미 전달된 요청이나 자격 증명은 회수할 수 없습니다.', 'Service access revoked.': '서비스 액세스가 취소되었습니다.'
  });
  Object.assign(i18n.messages, {
    'Unable to load provider settings. Close and reopen before creating access.': '제공자 설정을 불러올 수 없습니다. 액세스를 만들기 전에 닫았다가 다시 여세요.', 'Unable to load connected OAuth access. Close and reopen before creating access.': '연결된 OAuth 액세스를 불러올 수 없습니다. 액세스를 만들기 전에 닫았다가 다시 여세요.', 'Unable to load service access grants.': '서비스 액세스 권한을 불러올 수 없습니다.'
  });
  Object.assign(i18n.messages, {
    'Provider: {provider}\nAccount: {account}\nGranted scopes:\n{scopes}': '제공자: {provider}\n계정: {account}\n부여된 범위:\n{scopes}'
  });
  Object.assign(i18n.messages, {
    '{name} (disabled)': '{name} (비활성화됨)'
  });
  Object.assign(i18n.messages, {
    'I reviewed this provider and its allowed operations. Store my key with these settings. This does not authorize a consumer service to use it.': '이 제공자와 허용된 작업을 검토했습니다. 이 설정으로 키를 저장합니다. 소비자 서비스의 사용을 허용하는 것은 아닙니다.',
    'Unable to load provider settings. Close and reopen to review them before saving. An existing key can still be revoked.': '제공자 설정을 불러올 수 없습니다. 저장하기 전에 닫았다가 다시 열어 설정을 검토하세요. 기존 키는 계속 취소할 수 있습니다.'
  });
})();
