apiVersion: v1
kind: ServiceAccount
metadata:
  name: ternal-goauthy
  namespace: ternal-auth
  labels:
    app.kubernetes.io/name: goauthy
    app.kubernetes.io/part-of: ternal
automountServiceAccountToken: false
