apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: standalone-goauthy-ingress
  namespace: goauthy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: goauthy
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: versity
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
