apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goauthy
  namespace: goauthy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: goauthy
          ports:
            - $patch: replace
            - name: http
              containerPort: 8080
          env:
            - name: GOAUTHY_RHIZA_PROFILE
              value: standalone
            - $patch: delete
              name: GOAUTHY_RHIZA_PEER_ADDR
            - $patch: delete
              name: GOAUTHY_RHIZA_MEMBERS
            - $patch: delete
              name: GOAUTHY_RHIZA_ADMIN_TOKEN
