apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../k8s
  - isolation-networkpolicy.yaml
patches:
  - path: fixture-sidecar-patch.yaml
  - path: fixture-namespace-patch.yaml
